package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javapop.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class BajaProducto extends javax.swing.JFrame {
    
    private JFrame principal;
    private ArrayList<Producto> productos = Utilidad.getLogged().getProductos();
    private DefaultListModel nombres = new DefaultListModel();
    public BajaProducto(JFrame ventana) {
        
        initComponents();
        ImageIcon imagenFondo = new ImageIcon("fondo.jpg");
        Icon iconoFondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(iconoFondo);
        this.repaint();
        ImageIcon imagenLogo = new ImageIcon("logo.png");
        Icon iconoLogo = new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_DEFAULT));
        lblLogo.setIcon(iconoLogo);
        this.repaint();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icono.png"));
        
        Utilidad.comprobarUrgente();
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        

        
        for (int i = 0; i < productos.size(); i++) {
            nombres.addElement(productos.get(i).getTitulo());  
        }  
        jList1.setModel(nombres);        
    
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelProductos1 = new gui.PanelProductos();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop - Baja de Productos");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(lblLogo);
        lblLogo.setBounds(970, 110, 370, 210);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tus productos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 40, 270, 42);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jButton1.setText("Baja");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 510, 320, 100);
        getContentPane().add(panelProductos1);
        panelProductos1.setBounds(410, 110, 620, 500);

        jList1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jList1.setAutoscrolls(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 330, 250);

        lblFondo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 1370, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jList1.isSelectionEmpty()){
        
           JOptionPane.showMessageDialog(this, " Debe seleccionar un producto ", "Error", JOptionPane.ERROR_MESSAGE);
        
        }else{
           Producto product;
           int x =  jList1.getSelectedIndex();
            
           product = productos.get(x);
           int resp = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el producto "+product.getTitulo()+"?", "Confirmación", JOptionPane.YES_NO_OPTION);
           if(resp==0){
           
              Utilidad.eliminarProducto(Utilidad.getLogged(), product);
              JOptionPane.showMessageDialog(this, "Producto dado de baja correctamente");
              nombres.removeElement(product.getTitulo());
              jList1.repaint();
              if(nombres.isEmpty()){
                  panelProductos1.limpiar();
              }
           }
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int indice = jList1.getSelectedIndex();
        if (indice<productos.size() && indice >= 0){
            panelProductos1.setDatos(productos.get(indice));
            panelProductos1.setImage(productos.get(indice).getImagen());
        }
    }//GEN-LAST:event_jList1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private gui.PanelProductos panelProductos1;
    // End of variables declaration//GEN-END:variables
}
