
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import javapop.Cliente;
import javapop.ClientePro;
import javapop.Utilidad;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class MejoraPro extends javax.swing.JFrame {
    
    private JFrame principal;
    private Cliente cli = null;
    private String tipo;
    public MejoraPro(JFrame ventana) {
        
        initComponents();
        ImageIcon imagenFondo = new ImageIcon("fondo.jpg");
        Icon iconoFondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(iconoFondo);
        this.repaint();
        ImageIcon imagenLogo = new ImageIcon("logo.png");
        Icon iconoLogo = new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(iconoLogo);
        this.repaint();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icono.png"));
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        
        tipo = Utilidad.getLogged().getClass().getSimpleName();
        if (!tipo.equals("Cliente")){
            ClientePro pro = (ClientePro) Utilidad.getLogged();
            descrip.setText(pro.getDescripcion());
            hora.setText(pro.getHorario());
            tlf.setText(String.valueOf(pro.getTlf()));
            pagina.setText(pro.getWeb());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        pagina = new javax.swing.JTextField();
        tlf = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        descrip1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop Profesional");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        aceptar.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar);
        aceptar.setBounds(100, 530, 240, 120);

        pagina.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pagina.setAlignmentY(2.0F);
        pagina.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(pagina);
        pagina.setBounds(100, 470, 260, 30);

        tlf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tlf.setAlignmentY(2.0F);
        tlf.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(tlf);
        tlf.setBounds(100, 390, 260, 30);

        hora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hora.setAlignmentY(2.0F);
        hora.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(hora);
        hora.setBounds(100, 300, 260, 30);

        descrip1.setAutoscrolls(true);

        descrip.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descrip1.setViewportView(descrip);

        jPanel1.add(descrip1);
        descrip1.setBounds(100, 140, 260, 120);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Página web");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 340, 300, 210);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 250, 300, 210);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Horario de apertura");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 170, 450, 210);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripción");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 0, 242, 210);
        jPanel1.add(lblLogo);
        lblLogo.setBounds(560, 30, 700, 610);

        lblFondo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String descripcion,horario,web;
        long tlf;
        if(tipo.equals("Cliente")){
            if (descrip.getText().equals("")
                    || hora.getText().equals("")
                    || this.tlf.getText().equals("")
                    || this.pagina.getText().equals("")) {




                JOptionPane.showMessageDialog(this, " Error: Debe rellenar todos los datos. ", "Error", JOptionPane.ERROR_MESSAGE);
            }else {

                try{
                    descripcion = descrip.getText();
                    horario = hora.getText();
                    tlf = Integer.parseInt(this.tlf.getText());
                    web = pagina.getText();
                    int resp = JOptionPane.showConfirmDialog(null, "¿Desea pagar 30€ y convertirse en cliente profesional?", "Confirmación", JOptionPane.YES_NO_OPTION);
                    if (resp == 0) {

                        JOptionPane.showMessageDialog(this, "Se han cargado 30€ a tu tarjeta: " + Utilidad.getLogged().getTarjeta());

                        if (Utilidad.mejoraCliente(Utilidad.getLogged(), descripcion, web, tlf, horario)) {

                            JOptionPane.showMessageDialog(this, "Enhorabuena. Ya eres un cliente profesional en JavaPop");
                            this.dispose();

                        } else {
                            JOptionPane.showMessageDialog(this, "Ha habido un error.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {

                        JOptionPane.showMessageDialog(this, "Si no pagas 30€ no puedes convertirte en cliente profesional ");

                    }

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "Excepción al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);

                }

            }
        }
        else{
            try{
                descripcion = descrip.getText();
                horario = hora.getText();
                tlf = Integer.parseInt(this.tlf.getText());
                web = pagina.getText();
                if(Utilidad.modificarDatosPro((ClientePro)Utilidad.getLogged(), descripcion, web, tlf, horario)){
                    JOptionPane.showMessageDialog(this, "Se han modificado tus datos correctamente");
                    this.dispose();
                }
                else{JOptionPane.showMessageDialog(this, "Error al modificar los datos.", "Mensaje", JOptionPane.ERROR_MESSAGE);}
            }
            catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "Excepción al modificar los datos.", "Mensaje", JOptionPane.ERROR_MESSAGE);

                }
        }


    }//GEN-LAST:event_aceptarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        VentanaCliente v = new VentanaCliente(this);
    }//GEN-LAST:event_formWindowClosed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextPane descrip;
    private javax.swing.JScrollPane descrip1;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField pagina;
    private javax.swing.JTextField tlf;
    // End of variables declaration//GEN-END:variables
}
