
package gui;

import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javapop.Producto;
import javapop.Utilidad;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



public class PanelProductos extends javax.swing.JPanel {


    public PanelProductos() {
        initComponents();
    }
    
    public void setDatos(Producto p){
        
        titulo.setText(p.getTitulo());
        desc.setText(p.getDescripcion());
        categoria.setText(p.getCategoria());
        estado.setText(p.getEstado());
        
        DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        String fn = p.getFecha().format(formatoCorto);
        fecha.setText(fn);
        
        postal.setText(p.getPostal());
        ciudad.setText(p.getCiudad());
        propietario.setText(p.getClient().getNombre());
        
        double precd = p.getPrecio();
        String precs = String.valueOf(precd);
        precio.setText(precs);
        
        if (p.isUrgente()){
            urgente.setText("Sí");
        }
        else{urgente.setText("No");}
    }

    public String getCategoria() {
        return categoria.getText();
    }

    public String getCiudad() {
        return ciudad.getText();
    }

    public String getDesc() {
        return desc.getText();
    }

    public String getEstado() {
        return estado.getText();
    }

    public String getPostal() {
        return postal.getText();
    }

    public String getTitulo() {
        return titulo.getText();
    }

    public double getPrecio() {
        String prec = precio.getText();
        double precd = Double.parseDouble(prec);
        return precd;
    }

    public JLabel getFoto() {
        return foto;
    }
    public boolean isUrgente(){
        String txt = urgente.getText();
        if (txt.equals("Sí")){return true;}
        else{return false;}
    }
    
    public void setFecha(LocalDate fecha){
        DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        String fn = fecha.format(formatoCorto);
        this.fecha.setText(fn);
    }
    public void setCategoria(String cat){
        categoria.setText(cat);
    }
    public void setEstado(String est){
        estado.setText(est);
    }
    public void setPostal(){
        postal.setText(Utilidad.getLogged().getPostal());
    }
    public void setCiudad(){
        ciudad.setText(Utilidad.getLogged().getCiudad());
    }
    public void setPropietario(){
        propietario.setText(Utilidad.getLogged().getNombre());
    }
    public void setUrgente(boolean conf){
        if(conf){urgente.setText("Sí");}
        else{urgente.setText("No");}
    }
    public void setImage(ImageIcon imagen){
        Image img = imagen.getImage();
        Image newImg = img.getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        foto.setIcon(image);
    }
    public void tituloEditable(boolean b){
        titulo.setEditable(b);
    }
    public void descripcionEditable(boolean b){
        desc.setEditable(b);
    }
    public void precioEditable(boolean b){
        precio.setEditable(b);
    }
    public void limpiar(){
        categoria.setText("");
        ciudad.setText("");
        desc.setText("");
        estado.setText("");
        fecha.setText("");
        postal.setText("");
        precio.setText("");
        propietario.setText("");
        titulo.setText("");
        urgente.setText("");
        foto.setIcon(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        urgente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        postal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        propietario = new javax.swing.JTextField();
        descripcion = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(42, 42, 42));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setLayout(null);
        add(foto);
        foto.setBounds(30, 10, 190, 160);

        titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(titulo);
        titulo.setBounds(10, 220, 230, 30);

        urgente.setEditable(false);
        urgente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(urgente);
        urgente.setBounds(350, 430, 230, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Urgente");
        add(jLabel1);
        jLabel1.setBounds(350, 400, 280, 28);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del producto");
        add(jLabel2);
        jLabel2.setBounds(10, 190, 231, 28);

        precio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(precio);
        precio.setBounds(350, 70, 230, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción del producto");
        add(jLabel3);
        jLabel3.setBounds(10, 250, 280, 28);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Categoría");
        add(jLabel4);
        jLabel4.setBounds(10, 400, 280, 28);

        categoria.setEditable(false);
        categoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(categoria);
        categoria.setBounds(10, 430, 230, 30);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");
        add(jLabel5);
        jLabel5.setBounds(350, 40, 280, 28);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado");
        add(jLabel8);
        jLabel8.setBounds(350, 100, 280, 28);

        estado.setEditable(false);
        estado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(estado);
        estado.setBounds(350, 130, 230, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de subida ");
        add(jLabel6);
        jLabel6.setBounds(350, 160, 280, 28);

        fecha.setEditable(false);
        fecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(fecha);
        fecha.setBounds(350, 190, 230, 30);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Postal");
        add(jLabel7);
        jLabel7.setBounds(350, 220, 280, 28);

        postal.setEditable(false);
        postal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(postal);
        postal.setBounds(350, 250, 230, 30);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ciudad");
        add(jLabel9);
        jLabel9.setBounds(350, 280, 280, 28);

        ciudad.setEditable(false);
        ciudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(ciudad);
        ciudad.setBounds(350, 310, 230, 30);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre del propietario");
        add(jLabel10);
        jLabel10.setBounds(350, 340, 280, 28);

        propietario.setEditable(false);
        propietario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(propietario);
        propietario.setBounds(350, 370, 230, 30);

        descripcion.setViewportView(desc);

        add(descripcion);
        descripcion.setBounds(10, 280, 230, 120);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextPane desc;
    private javax.swing.JScrollPane descripcion;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField postal;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField propietario;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField urgente;
    // End of variables declaration//GEN-END:variables
}
