
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.ListIterator;
import javapop.Utilidad;
import javapop.Venta;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VentanaConsultaVentas extends javax.swing.JFrame {
    
    private JFrame principal;
    private Venta venta = null;
    private ArrayList<Venta> ventaux; 
    private ListIterator<Venta> li; 
    private String total,actual;
    public VentanaConsultaVentas(JFrame ventana) {
        
        initComponents();
        ImageIcon imagenFondo = new ImageIcon("fondo.jpg");
        Icon iconoFondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(iconoFondo);
        this.repaint();
        ImageIcon imagenLogo = new ImageIcon("logo.png");
        Icon iconoLogo = new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(iconoLogo);
        this.repaint();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icono.png"));
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);  
        
        LocalDate ld =LocalDate.of(2000, Month.JANUARY, 01);
        Instant instant = ld.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant();
        Date dia = Date.from(instant);
        setjSpinnerFecha(dia);
    }
    
    
    private void consultarTodo() {
        try {

            ventaux = Utilidad.getVentas();
            li = ventaux.listIterator();
            total = String.valueOf(ventaux.size());
            if (ventaux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                siguiente.setEnabled(false);
                anterior.setEnabled(false);
                return;
            } else {
                siguiente.setEnabled(true);
                anterior.setEnabled(true);
                todas.setEnabled(true);
                buscfecha.setEnabled(true);
            }
            if (li.hasNext()) {
                venta = (Venta)li.next();
                actual = String.valueOf(ventaux.indexOf(venta) + 1);
            }
            if (venta != null) {
                presenta(venta);
            } else {
                JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }
    
    private void consultarPorFecha(LocalDate fecha){
        try {

            ventaux = Utilidad.busquedaVentas(fecha);
            li = ventaux.listIterator();
            total = String.valueOf(ventaux.size());
            if (ventaux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                siguiente.setEnabled(false);
                anterior.setEnabled(false);
                panelVentas1.limpiar();
                recuento.setText("0/0");
                return;
            } else {
                siguiente.setEnabled(true);
                anterior.setEnabled(true);
                todas.setEnabled(true);
                buscfecha.setEnabled(true);
            }
            if (li.hasNext()) {
                venta = (Venta)li.next();
                actual = String.valueOf(ventaux.indexOf(venta) + 1);
            }
            if (venta != null) {
                presenta(venta);
                recuento.setText(actual + "/" + total);
            } else {
                JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }
    
    public void presenta(Venta v){
        panelVentas1.setDatos(v);
    }
    public void setjSpinnerFecha(Date d) {
        this.jSpinnerFecha.setValue(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recuento = new javax.swing.JLabel();
        panelVentas1 = new gui.PanelVentas();
        jSpinnerFecha = new javax.swing.JSpinner();
        todas = new javax.swing.JButton();
        buscfecha = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop Consulta de Ventas");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        recuento.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        recuento.setForeground(new java.awt.Color(255, 255, 255));
        recuento.setText("0/0");
        jPanel1.add(recuento);
        recuento.setBounds(260, 20, 130, 60);
        jPanel1.add(panelVentas1);
        panelVentas1.setBounds(20, 90, 574, 430);

        jSpinnerFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(-3600000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha);
        jSpinnerFecha.setBounds(500, 530, 330, 70);

        todas.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        todas.setText("Buscar Todas las Ventas");
        todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasActionPerformed(evt);
            }
        });
        jPanel1.add(todas);
        todas.setBounds(20, 620, 450, 70);

        buscfecha.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        buscfecha.setText("Buscar Ventas por Fecha");
        buscfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscfechaActionPerformed(evt);
            }
        });
        jPanel1.add(buscfecha);
        buscfecha.setBounds(20, 530, 450, 70);

        anterior.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(anterior);
        anterior.setBounds(20, 30, 220, 50);

        siguiente.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente);
        siguiente.setBounds(340, 30, 220, 50);
        jPanel1.add(lblLogo);
        lblLogo.setBounds(660, 60, 590, 460);

        lblFondo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        if (li.hasNext()) {
        venta = li.next();
        if (venta != null) {
            presenta(venta);
            actual = String.valueOf(ventaux.indexOf(venta) + 1);
            recuento.setText(actual + "/" + total);
        } else {
            JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        if (li.hasPrevious()) {
        venta = li.previous();
        if (venta != null) {
            presenta(venta);
            actual = String.valueOf(ventaux.indexOf(venta) + 1);
            recuento.setText(actual + "/" + total);
        } else {
            JOptionPane.showMessageDialog(this, "No hay ventas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_anteriorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void todasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasActionPerformed
        consultarTodo();
        if(ventaux.size() == 0){actual = "0";}
        recuento.setText(actual + "/" + total);
    }//GEN-LAST:event_todasActionPerformed

    private void buscfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscfechaActionPerformed
        Date fecha = (Date) jSpinnerFecha.getValue();
        Instant instant = Instant.ofEpochMilli(fecha.getTime());
        LocalDate localDate = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalDate();
        consultarPorFecha(localDate);
        
    }//GEN-LAST:event_buscfechaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton buscfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private gui.PanelVentas panelVentas1;
    private javax.swing.JLabel recuento;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton todas;
    // End of variables declaration//GEN-END:variables
}
