
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.ListIterator;
import javapop.Producto;
import javapop.Utilidad;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VentanaConsultaProductos extends javax.swing.JFrame {
    
    private JFrame principal;
    private Producto prod = null;
    private ArrayList<Producto> prodaux; 
    private ListIterator<Producto> li; 
    private String total,actual;
    public VentanaConsultaProductos(JFrame ventana) {
        
        initComponents();
        ImageIcon imagenFondo = new ImageIcon("fondo.jpg");
        Icon iconoFondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(iconoFondo);
        this.repaint();
        ImageIcon imagenLogo = new ImageIcon("logo.png");
        Icon iconoLogo = new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(iconoLogo);
        this.repaint();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icono.png"));
        
        Utilidad.comprobarUrgente();
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        
        consultarTodo();
        panelProductos1.tituloEditable(false);
        panelProductos1.descripcionEditable(false);
        panelProductos1.precioEditable(false);
        recuento.setText(actual + "/" + total);
        
    }
    
    /** Consulta los productos del ArrayList ordenados para su presentación */
    private void consultarTodo() {
        try {

            prodaux = Utilidad.getProductos();
            li = prodaux.listIterator();
            total = String.valueOf(prodaux.size());
            if (prodaux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                siguiente.setEnabled(false);
                anterior.setEnabled(false);
                actual = "0";
                total = "0";
                return;
            } else {
                siguiente.setEnabled(true);
                anterior.setEnabled(true);
                baja.setEnabled(true);
            }
            if (li.hasNext()) {
                prod = (Producto) li.next();
                actual = String.valueOf(prodaux.indexOf(prod) + 1);
            }
            if (prod != null) {
                presenta(prod);
            } else {
                JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }
    
    public void presenta(Producto p){
        panelProductos1.setDatos(p);
        panelProductos1.setImage(p.getImagen());         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelProductos1 = new gui.PanelProductos();
        recuento = new javax.swing.JLabel();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop Consulta de Productos");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);
        jPanel1.add(panelProductos1);
        panelProductos1.setBounds(60, 150, 610, 470);

        recuento.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        recuento.setForeground(new java.awt.Color(255, 255, 255));
        recuento.setText("1/10");
        jPanel1.add(recuento);
        recuento.setBounds(330, 80, 130, 60);

        anterior.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(anterior);
        anterior.setBounds(90, 90, 220, 50);

        siguiente.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente);
        siguiente.setBounds(410, 90, 220, 50);

        baja.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        baja.setText("Baja");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });
        jPanel1.add(baja);
        baja.setBounds(90, 630, 290, 70);
        jPanel1.add(lblLogo);
        lblLogo.setBounds(710, 160, 540, 440);

        lblFondo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        
        if (prod != null) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el producto seleccionado?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (resp == 0){ 
                li.remove();
                Utilidad.eliminarProducto(prod.getClient(), prod);
                prod.getClient().borrarProducto(prod);
                JOptionPane.showMessageDialog(this, "El producto ha sido dado de baja con éxito.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);    
            }
            else{JOptionPane.showMessageDialog(this, "El producto no se ha dado de baja.", "Mensaje", JOptionPane.INFORMATION_MESSAGE); }
        }else {
        JOptionPane.showMessageDialog(this, " Error: - Producto no encontrado - ", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
        if (li.hasNext()) {
        prod = (Producto)li.next();
        if (prod != null) {
            presenta(prod);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    } else if (li.hasPrevious()) {
        prod = (Producto)li.previous();
        if (prod != null) {
            presenta(prod);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    else{
        panelProductos1.limpiar();
        prod = null;
    }
        total = String.valueOf(prodaux.size());
        if(prodaux.size() == 0){
            actual = "0";
        }
        else{actual = String.valueOf(prodaux.indexOf(prod) + 1);}
        recuento.setText(actual + "/" + total);
    }//GEN-LAST:event_bajaActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        if (li.hasNext()) {
        prod = li.next();
        if (prod != null) {
            presenta(prod);
            actual = String.valueOf(prodaux.indexOf(prod) + 1);
            recuento.setText(actual + "/" + total);
        } else {
            JOptionPane.showMessageDialog(this, "No hay personas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        if (li.hasPrevious()) {
        prod = li.previous();
        if (prod != null) {
            presenta(prod);
            actual = String.valueOf(prodaux.indexOf(prod) + 1);
            recuento.setText(actual + "/" + total);
        } else {
            JOptionPane.showMessageDialog(this, "No hay personas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_anteriorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton baja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private gui.PanelProductos panelProductos1;
    private javax.swing.JLabel recuento;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
