
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import javapop.Cliente;
import javapop.Utilidad;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VentanaRegistro extends javax.swing.JFrame {
    
    private JFrame principal;
    private Cliente cli = null;

    public VentanaRegistro(JFrame ventana) {
        
        initComponents();
        ImageIcon imagenFondo = new ImageIcon("fondo.jpg");
        Icon iconoFondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(iconoFondo);
        this.repaint();
        ImageIcon imagenLogo = new ImageIcon("logo.png");
        Icon iconoLogo = new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(iconoLogo);
        this.repaint();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icono.png"));
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        tarjeta = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        postal = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop Registro");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        aceptar.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar);
        aceptar.setBounds(1000, 590, 240, 120);

        tarjeta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tarjeta.setAlignmentY(2.0F);
        tarjeta.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(tarjeta);
        tarjeta.setBounds(90, 630, 260, 30);

        ciudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ciudad.setAlignmentY(2.0F);
        ciudad.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(ciudad);
        ciudad.setBounds(90, 540, 260, 30);

        postal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        postal.setAlignmentY(2.0F);
        postal.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(postal);
        postal.setBounds(90, 450, 260, 30);

        nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombre.setAlignmentY(2.0F);
        nombre.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(nombre);
        nombre.setBounds(90, 360, 260, 30);

        dni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dni.setAlignmentY(2.0F);
        dni.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(dni);
        dni.setBounds(90, 280, 260, 30);

        pass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pass.setAlignmentY(2.0F);
        pass.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(pass);
        pass.setBounds(90, 200, 260, 30);

        user.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user.setAlignmentY(2.0F);
        user.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jPanel1.add(user);
        user.setBounds(90, 120, 260, 30);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tarjeta de Crédito");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 490, 430, 210);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código Postal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 310, 300, 210);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 230, 300, 210);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DNI");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 150, 300, 210);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 70, 300, 210);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ciudad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 400, 300, 210);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, -10, 210, 210);
        jPanel1.add(lblLogo);
        lblLogo.setBounds(580, 80, 670, 460);

        lblFondo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String correo, contra, dni, nombre, postal, ciudad, tarjeta;
        if (user.getText().equals("") ||
                pass.getText().equals("") ||
                this.dni.getText().equals("") ||
                this.nombre.getText().equals("") ||
                this.postal.getText().equals("") ||
                this.ciudad.getText().equals("") ||
                this.tarjeta.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, " Error: Debe rellenar todos los datos. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            try{
                correo = user.getText();
                contra = pass.getText();
                dni = this.dni.getText();
                nombre = this.nombre.getText();
                postal = this.postal.getText();
                ciudad = this.ciudad.getText();
                tarjeta = this.tarjeta.getText();
                if (correo.equals("admin@javapop.com")){
                    JOptionPane.showMessageDialog(this, "No puede usar este correo electrónico", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(postal.length() >= 3){
                        cli = new Cliente(correo, contra, dni, nombre, postal, ciudad, tarjeta);

                        if (Utilidad.registroCliente(cli)){
                            JOptionPane.showMessageDialog(this, "Ha sido registrado con éxito.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                            
                        }
                        else{JOptionPane.showMessageDialog(this, "Ya hay registrada una persona con este correo electrónico o DNI. Por favor no"
                                + " suplante la identidad de nadie, o escoja otro e-mail. Gracias", "Mensaje", JOptionPane.ERROR_MESSAGE);}
                    }
                    else{JOptionPane.showMessageDialog(this, " Error: Recuerda que el código postal debe tener"
                            + "al menos tres dígitos. ", "Error", JOptionPane.ERROR_MESSAGE);}
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Excepción al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField postal;
    private javax.swing.JTextField tarjeta;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
